"""
Unit tests for the OMX Task Queue.

Generated by OMX agentic team demo (Worker 2).
These tests use mock Redis to run without a Redis server.
"""

import unittest
from unittest.mock import MagicMock, patch
from omx_integration.task_queue import Task, TaskStatus


class TestTask(unittest.TestCase):
    """Tests for the Task data class."""

    def test_create_task(self):
        task = Task(
            task_id="test-001",
            subject="Test task",
            description="A test",
        )
        self.assertEqual(task.task_id, "test-001")
        self.assertEqual(task.subject, "Test task")
        self.assertEqual(task.status, TaskStatus.PENDING)
        self.assertEqual(task.version, 1)

    def test_task_roundtrip(self):
        """Task should survive dict serialization roundtrip."""
        original = Task(
            task_id="test-002",
            subject="Roundtrip",
            description="Testing serialization",
            owner="worker-1",
        )
        data = original.to_dict()
        restored = Task.from_dict(data)
        self.assertEqual(restored.task_id, original.task_id)
        self.assertEqual(restored.subject, original.subject)
        self.assertEqual(restored.status, original.status)
        self.assertEqual(restored.owner, original.owner)

    def test_status_enum_values(self):
        """TaskStatus should have exactly 5 states."""
        self.assertEqual(TaskStatus.PENDING.value, "pending")
        self.assertEqual(TaskStatus.IN_PROGRESS.value, "in_progress")
        self.assertEqual(TaskStatus.COMPLETED.value, "completed")
        self.assertEqual(TaskStatus.FAILED.value, "failed")
        self.assertEqual(TaskStatus.CANCELLED.value, "cancelled")


class TestTaskLifecycle(unittest.TestCase):
    """Tests for the claim-safe task lifecycle."""

    def test_task_status_transitions(self):
        """Verify valid task status transitions."""
        task = Task(task_id="lc-001", subject="Lifecycle")

        # pending -> in_progress
        self.assertEqual(task.status, TaskStatus.PENDING)
        task.status = TaskStatus.IN_PROGRESS
        self.assertEqual(task.status, TaskStatus.IN_PROGRESS)

        # in_progress -> completed
        task.status = TaskStatus.COMPLETED
        self.assertEqual(task.status, TaskStatus.COMPLETED)

    def test_claim_token_generation(self):
        """Claim tokens should be non-empty strings."""
        import uuid
        token = str(uuid.uuid4())[:12]
        self.assertEqual(len(token), 12)
        self.assertTrue(token.isalnum() or "-" in token)


if __name__ == "__main__":
    unittest.main()
