"""
Unit tests for the OMX Skill Router.

Generated by OMX agentic team demo (Worker 2).
"""

import unittest
from omx_integration.skill_router import SkillRouter, SKILL_DEFINITIONS


class TestSkillRouter(unittest.TestCase):
    """Tests for keyword detection and skill routing."""

    def setUp(self):
        self.router = SkillRouter(omx_runtime=False)

    def test_explicit_invocation(self):
        """$name invocations should match directly."""
        result = self.router.route('$plan "implement auth module"')
        self.assertIsNotNone(result)
        self.assertEqual(result["skill"], "plan")
        self.assertFalse(result["blocked"])

    def test_keyword_match_case_insensitive(self):
        """Keywords should match case-insensitively."""
        result = self.router.route("Let's Plan The authentication module")
        self.assertIsNotNone(result)
        self.assertEqual(result["skill"], "plan")

    def test_runtime_only_blocked(self):
        """Runtime-only skills should be blocked outside OMX runtime."""
        result = self.router.route("$team 3:executor fix tests")
        self.assertIsNotNone(result)
        self.assertTrue(result["blocked"])

    def test_runtime_only_allowed(self):
        """Runtime-only skills should work inside OMX runtime."""
        runtime_router = SkillRouter(omx_runtime=True)
        result = runtime_router.route("$team 3:executor fix tests")
        self.assertIsNotNone(result)
        self.assertFalse(result["blocked"])

    def test_no_match(self):
        """Unrecognized messages should return None."""
        result = self.router.route("hello world how are you")
        self.assertIsNone(result)

    def test_most_specific_wins(self):
        """Longer keyword matches should win over shorter ones."""
        result = self.router.route("deep interview the team about requirements")
        self.assertIsNotNone(result)
        self.assertEqual(result["skill"], "deep-interview")

    def test_explicit_overrides_keyword(self):
        """Explicit $name should override non-explicit keyword matches."""
        result = self.router.route("$analyze investigate the build errors")
        self.assertIsNotNone(result)
        self.assertEqual(result["skill"], "analyze")

    def test_list_skills(self):
        """list_skills should return all skill definitions."""
        skills = self.router.list_skills()
        self.assertGreater(len(skills), 0)
        names = [s["name"] for s in skills]
        self.assertIn("plan", names)
        self.assertIn("team", names)

    def test_handler_registration(self):
        """Registered handlers should appear in route results."""
        def mock_handler(task):
            pass
        self.router.register_handler("plan", mock_handler)
        result = self.router.route("$plan test")
        self.assertIsNotNone(result)
        self.assertEqual(result["handler"], mock_handler)

    def test_security_review_match(self):
        """Security review keyword should match."""
        result = self.router.route("run a security review on the API")
        self.assertIsNotNone(result)
        self.assertEqual(result["skill"], "security-review")

    def test_cancel_match(self):
        """Cancel keyword should match."""
        result = self.router.route("cancel the current operation")
        self.assertIsNotNone(result)
        self.assertEqual(result["skill"], "cancel")


class TestSkillDefinitions(unittest.TestCase):
    """Tests for the skill definition catalog."""

    def test_all_definitions_have_required_fields(self):
        """Each skill definition must have keywords, description, runtime_only."""
        for name, defn in SKILL_DEFINITIONS.items():
            self.assertIn("keywords", defn, f"{name} missing keywords")
            self.assertIn("description", defn, f"{name} missing description")
            self.assertIn("runtime_only", defn, f"{name} missing runtime_only")
            self.assertIsInstance(defn["keywords"], list)
            self.assertGreater(len(defn["keywords"]), 0, f"{name} has no keywords")

    def test_no_duplicate_keywords_across_skills(self):
        """Keywords should not appear in multiple skill definitions."""
        seen = {}
        for name, defn in SKILL_DEFINITIONS.items():
            for kw in defn["keywords"]:
                kw_lower = kw.lower()
                if kw_lower in seen:
                    # Allow overlapping substrings but not exact duplicates
                    self.assertNotEqual(
                        seen[kw_lower], name,
                        f"Duplicate keyword '{kw}' in {name}"
                    )
                seen[kw_lower] = name


if __name__ == "__main__":
    unittest.main()
