"""
OMX Team Utilities — Helper functions for team operations.

Generated by OMX agentic team demo (Worker 1).
"""

import hashlib
import json
import os
import time
import uuid
from datetime import datetime, timezone
from typing import Any


def generate_task_id(prefix: str = "task") -> str:
    """Generate a unique task ID with optional prefix."""
    short_uuid = str(uuid.uuid4())[:8]
    return f"{prefix}-{short_uuid}"


def generate_correlation_id() -> str:
    """
    Generate a VaultWares-style CorrelationId.
    Format: 7-character alphanumeric starting with lowercase 'c'.
    """
    raw = uuid.uuid4().hex[:6]
    return f"c{raw}"


def format_timestamp(epoch: float = None) -> str:
    """Format an epoch timestamp as ISO 8601 UTC string."""
    if epoch is None:
        epoch = time.time()
    dt = datetime.fromtimestamp(epoch, tz=timezone.utc)
    return dt.isoformat()


def format_duration(seconds: float) -> str:
    """Format a duration in seconds to a human-readable string."""
    if seconds < 60:
        return f"{seconds:.1f}s"
    minutes = int(seconds // 60)
    remaining = seconds % 60
    if minutes < 60:
        return f"{minutes}m {remaining:.0f}s"
    hours = int(minutes // 60)
    remaining_min = minutes % 60
    return f"{hours}h {remaining_min}m"


def build_redis_message(
    agent_id: str,
    action: str,
    task: str = "",
    target: str = "",
    **details: Any,
) -> dict:
    """
    Build a standardized Redis message dict.

    Follows the VaultWares Agentciation message schema:
    {agent, action, task, target, details, timestamp, correlation_id}
    """
    return {
        "agent": agent_id,
        "action": action,
        "task": task,
        "target": target,
        "details": details,
        "timestamp": format_timestamp(),
        "correlation_id": generate_correlation_id(),
    }


def safe_write_file(path: str, content: str, create_dirs: bool = True) -> bool:
    """
    Safely write content to a file with optional directory creation.

    Returns True on success, False on failure.
    """
    try:
        if create_dirs:
            os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        return True
    except OSError:
        return False


def compute_file_hash(path: str) -> str:
    """Compute SHA-256 hash of a file's contents."""
    sha256 = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            sha256.update(chunk)
    return sha256.hexdigest()


def json_dumps_safe(obj: Any, indent: int = 2) -> str:
    """JSON serialize with safe defaults (no ASCII escaping, sorted keys)."""
    return json.dumps(obj, indent=indent, ensure_ascii=False, sort_keys=True, default=str)
